version: "3.8"

services:
  gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - productos
      - inventario
    networks:
      - app_net

  productos_db:
    image: postgres:15
    container_name: productos_db
    environment:
      POSTGRES_USER: productos_user
      POSTGRES_PASSWORD: productos_pass
      POSTGRES_DB: productos_db
    volumes:
      - productos_data:/var/lib/postgresql/data
    networks:
      - app_net

  inventario_db:
    image: postgres:15
    container_name: inventario_db
    environment:
      POSTGRES_USER: inventario_user
      POSTGRES_PASSWORD: inventario_pass
      POSTGRES_DB: inventario_db
    volumes:
      - inventario_data:/var/lib/postgresql/data
    networks:
      - app_net

  productos:
    build: ./productos
    container_name: productos_app
    depends_on:
      - productos_db
    networks:
      - app_net

  inventario:
    build: ./inventario
    container_name: inventario_app
    depends_on:
      - inventario_db
      - productos
    networks:
      - app_net

volumes:
  productos_data:
  inventario_data:


networks:
  app_net:
