services:
  gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - productos
      # - inventario
    networks:
      - app_net

  productos_db:
    image: postgres:15
    container_name: productosdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productosdb
    volumes:
      - productos_data:/var/lib/postgresql/data
    networks:
      - app_net

  inventario_db:
    image: postgres:15
    container_name: inventario_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventariodb
    volumes:
      - inventario_data:/var/lib/postgresql/data
    networks:
      - app_net

  productos:
    build: ./ms-productos
    container_name: productos_app
    depends_on:
      - productos_db
    networks:
      - app_net
  # inventario:
  #   build: ./inventario
  #   container_name: inventario_app
  #   depends_on:
  #     - inventario_db
  #     - productos
  #   networks:
  #     - app_net

volumes:
  productos_data:
  inventario_data:


networks:
  app_net:
